name: Polaris Build to test Gradle User Home restore
on:
  push:
    paths:
      - '.github/workflows/polaris.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on:
      - self-hosted
    strategy:
      fail-fast: false
      matrix:
        storage:
          - fast-disk
          - slow-disk
        state:
          - javaCompile-restored
          - javaCompile-removed
        incremental_compile:
          - incremental-disabled
          - incremental-enabled
        gradle-executable:
          - "gradle-9.3.1"
          - "patched-gradle"
    env:
      GRADLE_USER_HOME: ${{ matrix.storage == 'fast-disk' && '/mnt/instance-store/gradle/HOME' || '/home/ec2-user/gradle/HOME' }}

    steps:
      - name: Cleanup home dir
        run: rm -rf $GRADLE_USER_HOME

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: corretto

      - uses: actions/checkout@v5
        with:
          repository: apache/polaris

      - uses: actions/checkout@v5
        with:
          path: custom-gradle

      - name: Disable incremental Java compile
        if: ${{ matrix.incremental_compile == 'incremental-disabled' }}
        run: |
          cat <<'EOF' >> build.gradle.kts

          allprojects { tasks.withType<JavaCompile>().configureEach { options.setIncremental(false) } }
          EOF

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: "9.3.1"
          develocity-injection-enabled: true
          develocity-plugin-version: '4.2.2'
          develocity-ccud-plugin-version: '2.4.0'
          develocity-url: 'https://ge.solutions-team.gradle.com'
          develocity-enforce-url: true
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

      - name: Remove javaCompile cache
        if: ${{ matrix.state == 'javaCompile-removed' }}
        run: rm -rf $GRADLE_USER_HOME/caches/9.3.1/javaCompile

      - name: Build with Gradle 9.3.1
        if: ${{ matrix.gradle-executable == 'gradle-9.3.1' }}
        run: ./gradlew --info --no-build-cache --no-daemon compileJava

      - name: Build with patched Gradle
        if: ${{ matrix.gradle-executable == 'patched-gradle' }}
        run: custom-gradle/gradle-fast/bin/gradle --info --no-build-cache --no-daemon compileJava
